name: adapter_design_pattern
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  xml: ^5.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
